name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 24]
    steps:
      - name: Setup (install dependencies)
        uses: ./.github/workflows/setup.yml
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests
        run: pnpm test:all
